# Generated by Django 4.1.1 on 2023-04-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fashionmartApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="buyer", old_name="pic4", new_name="pic",),
        migrations.AlterField(
            model_name="buyer",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
