# Generated by Django 4.1.1 on 2023-04-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fashionmartApp", "0003_alter_buyer_addressline3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="addressline3",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fashionmartApp.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fashionmartApp.buyer",
                    ),
                ),
            ],
        ),
    ]
