# Generated by Django 4.1.1 on 2023-04-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fashionmartApp", "0004_alter_buyer_addressline3_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist", old_name="name", new_name="product",
        ),
    ]
