# Generated by Django 4.1.1 on 2023-04-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fashionmartApp", "0005_rename_name_wishlist_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="addressline3",
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(name="Wishlist",),
    ]
