# Generated by Django 4.1.1 on 2023-04-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fashionmartApp", "0007_whislist"),
    ]

    operations = [
        migrations.RenameModel(old_name="Whislist", new_name="Wishlist",),
    ]
