# Generated by Django 4.1.1 on 2023-04-16 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fashionmartApp", "0009_checkout"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="orderstatus",
            field=models.IntegerField(
                choices=[
                    (0, "Order Placed"),
                    (1, "Not Packed"),
                    (2, "Packed"),
                    (3, "Ready to Shipped"),
                    (4, "Shipped"),
                    (5, "Out for Delivery"),
                    (6, "Delivered"),
                    (7, "Cancelled"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="paymentmode",
            field=models.IntegerField(
                choices=[(0, "COD"), (1, "Net Banking")], default=0
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="paymentstatus",
            field=models.IntegerField(choices=[(0, "Pending"), (1, "Done")], default=0),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="CheckoutProduct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fashionmartApp.checkout",
                    ),
                ),
                (
                    "p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fashionmartApp.product",
                    ),
                ),
            ],
        ),
    ]
