# Generated by Django 4.1.1 on 2023-04-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fashionmartApp", "0010_checkout_orderstatus_checkout_paymentmode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutproduct",
            name="qty",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="checkoutproduct",
            name="total",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
