# Generated by Django 4.1.1 on 2023-04-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fashionmartApp", "0011_checkoutproduct_qty_checkoutproduct_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "COD"), (1, "Net Banking")], default=0
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
