# Generated by Django 4.1.1 on 2023-04-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fashionmartApp", "0012_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer", name="otp", field=models.IntegerField(default=-15151),
        ),
    ]
