# Generated by Django 4.1.1 on 2023-04-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fashionmartApp", "0013_buyer_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer", name="otp", field=models.IntegerField(default=-1151515),
        ),
    ]
